### Site info:
title: archnfoss
tagline: A Blog about Arch Linux, Open Source Software, and Android Adventures
author: Austin (gtbjj)
email:
description: "A Blog about Arch Linux, Open Source Software, and Android Adventures" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Arch, Linux, Android, FOSS, Open Source, Software, Programming, Development"
url: "https://archnfoss.com" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username:
github_username:  gtbjj
instagram_username: southeastdirtbag
googleplus_username: AustinHaedicke
linkedin_username: austinhaedicke
disqus_shortname: gtbjj
favicon:     "/images/favicon.ico"
aboutme:  I like to play system admin in my free time and tinker with thngs. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/favicon.ico" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: ""
      Categories: "Categories"
      Recent_Posts: ""
      Tags: "Tags"
      Copyright_Notice: "Copyright Notice"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

#Blogroll:
#    - name: Austin
#      href: http://archnfoss.com
#      title: archnfoss

### Build settings
markdown: redcarpet
# highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

analytics:
  provider: google
  google:
    tracking_id: 'UA-63934221-2'
